name: Azure Login and Verification

on:
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI
permissions:
        id-token: write
        contents: read

jobs:
  azure-authentication:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate the Service Principal via OIDC
      - name: Login via Az module
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      # Verify the login was successful
      - name: Azure CLI script
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
